# ChiFlow paths configuration - keeps all outputs within the chiflow directory
# path to root directory (chiflow folder)
root_dir: .

# path to data directory
data_dir: ${paths.root_dir}/data/

# path to logging directory - confined to chiflow folder
log_dir: ${paths.root_dir}/logs/

# path for test predictions
test_predictions_filepath: ${paths.log_dir}/test/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}

# path to output directory, created dynamically by hydra - kept within chiflow
# path generation pattern is specified in `configs/hydra/default.yaml`
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}
